# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Enigma
tagline:             'The Puzzle Blog'
description:         'A collection of some awesome puzzles which I have encountered Made by  <a href="https://twitter.com/mdo" target="_blank">@kedar</a>.'
url:    http://kedartatwawadi.com/puzzleblog/
baseurl:        http://kedartatwawadi.com/puzzleblog/
rooturl:        http://kedartatwawadi.com/puzzleblog
paginate:            5

# About/contact
author:
  name:              Kedar Tatwawadi
  url:               http://kedartatwawadi.com
  email:             ktatwawadi@gmail.com

# Custom vars
version:             1.0.0

# plugins
gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

