#
#Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Puzzle Blog
tagline:          The Puzz Blog
url:              http://kedartatwawadi.com/puzzleblog
paginate:         1
baseurl:          http://kedartatwawadi.com/puzzleblog/
author:
  name:           Kedar Tatwawadi
  url:            https://twitter.com/kedar
  email:          ktatwawadi@gmail.com
markdown:         redcarpet
          
# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/kedartatwawadi/puzzleblog
